version: '3.9'

networks:
  grafana_loki:
  grafana_prometheus:

services:
  #==============================================>>> grafana
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    networks:
      - grafana_loki
  #==============================================>>> loki
  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - grafana_loki
  #==============================================>>> promtail
  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - 9080:9080
    networks:
      - grafana_loki
  #==============================================>>> prometheus
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - grafana_prometheus
  #==============================================>>> node exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - grafana_prometheus
    restart: unless-stopped
  #==============================================>>> alert manager 
  alertmanager:
    image: prom/alertmanager:v0.12.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: unless-stopped
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    networks:
      - grafana_prometheus
  #==============================================>>> cadvisor 
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - grafana_prometheus
